### ISSUE TITLE
Failing after fresh install with SQLAlchemy 1.4

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#189]
After a recent and fresh install the following error occurs when starting with `egon-data serve`

```
egon-data serve
/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/configuration.py:767: DeprecationWarning: You have two airflow.cfg files: /home/local/RL-INSTITUT/guido.plessmann/airflow/airflow.cfg and /home/local/RL-INSTITUT/guido.plessmann/egon-data-sh/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/local/RL-INSTITUT/guido.plessmann/egon-data-sh/airflow/airflow.cfg, and you should remove the other file
  category=DeprecationWarning,
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/bin/cli.py", line 82, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/app.py", line 42, in <module>
    from airflow.www.blueprints import routes
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/utils.py", line 40, in <module>
    import flask_admin.contrib.sqla.filters as sqlafilters
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
    from flask_admin.contrib.sqla.tools import is_relationship
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 4, in <module>
    from sqlalchemy.ext.declarative.clsregistry import _class_resolver
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'
/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/configuration.py:767: DeprecationWarning: You have two airflow.cfg files: /home/local/RL-INSTITUT/guido.plessmann/airflow/airflow.cfg and /home/local/RL-INSTITUT/guido.plessmann/egon-data-sh/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/local/RL-INSTITUT/guido.plessmann/egon-data-sh/airflow/airflow.cfg, and you should remove the other file
  category=DeprecationWarning,
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/bin/cli.py", line 82, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/app.py", line 42, in <module>
    from airflow.www.blueprints import routes
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/www/utils.py", line 40, in <module>
    import flask_admin.contrib.sqla.filters as sqlafilters
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
    from flask_admin.contrib.sqla.tools import is_relationship
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 4, in <module>
    from sqlalchemy.ext.declarative.clsregistry import _class_resolver
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'

```

This is probably due to the new version of SQLAlchemy 1.4 that was released recently. Introducing the upper version limit for SQLAlchemy like `sqlalchemy<1.4` solves the problem.
But still, we should make eGon-data work with SQLAlchemy 1.4 on the long run.

**Comment by gnn** [comment]
Figured out why this occurs. See the commit message for an explanation. Looks like Airflow 2.0 relaxes the constraints, so we can revisit the issue when we migrated to that.

**Comment by gplssm** [comment]
> Figured out why this occurs. See the commit message for an explanation. Looks like Airflow 2.0 relaxes the constraints, so we can revisit the issue when we migrated to that.

Thanks for researching that!
