### ISSUE TITLE
osmTGmod fails because of missing table

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#191]
During a run on an RLI server (test mode) everyting completed successfully except for the task osmtgmod.

Some log for context

```
[2021-03-31 12:24:37,589] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Executing SQL statement 279:
UPDATE branch_data SET cables = 6 WHERE cables = 4
[2021-03-31 12:24:37,602] {__init__.py:516} INFO - Executing SQL statement 280:
UPDATE branch_data SET cables = 6 WHERE cables = 7

[2021-03-31 12:24:37,602] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Executing SQL statement 280:
UPDATE branch_data SET cables = 6 WHERE cables = 7
[2021-03-31 12:24:37,614] {__init__.py:543} INFO - Power-script executed successfully.
[2021-03-31 12:24:37,614] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Power-script executed successfully.
[2021-03-31 12:24:37,614] {__init__.py:545} INFO - Saving Results...
[2021-03-31 12:24:37,615] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Saving Results...
[2021-03-31 12:24:37,820] {__init__.py:549} INFO - Abstraction process complete!
[2021-03-31 12:24:37,820] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Abstraction process complete!
[2021-03-31 12:24:37,821] {__init__.py:554} INFO - Writing results
[2021-03-31 12:24:37,821] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Writing results
[2021-03-31 12:24:37,821] {__init__.py:558} INFO - writing bus_data...
[2021-03-31 12:24:37,821] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 writing bus_data...
[2021-03-31 12:24:37,822] {__init__.py:561} INFO - Writing contents of table bus_data to /home/local/RL-INSTITUT/guido.plessmann/git-repos/eGon-data/src/egon/data/processing/osmtgmod/osmTGmod/egon-data/results/bus_data.csv...
[2021-03-31 12:24:37,822] {logging_mixin.py:120} WARNING - 03/31/2021 12:24:37 Writing contents of table bus_data to /home/local/RL-INSTITUT/guido.plessmann/git-repos/eGon-data/src/egon/data/processing/osmtgmod/osmTGmod/egon-data/results/bus_data.csv...
[2021-03-31 12:24:37,832] {taskinstance.py:1150} ERROR - relation "results.bus_data" does not exist
LINE 1: COPY (SELECT * FROM results.bus_data ) TO STDOUT WITH DELIMI...
                            ^
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 53, in run_osmtgmod
    docker_db_config=docker_db_config,
  File "/home/local/RL-INSTITUT/guido.plessmann/git-repos/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 569, in osmtgmod
    cur.copy_expert(outputquery, fh)
psycopg2.errors.UndefinedTable: relation "results.bus_data" does not exist
LINE 1: COPY (SELECT * FROM results.bus_data ) TO STDOUT WITH DELIMI...
                            ^

```

Once this is fixed, I gonna retry and, if successful, I'll give it a try for the entire dataset.

**Comment by ulfmueller** [comment]
that's weird. I don't get that one. I will have a look at it!
