### ISSUE TITLE
Temporary MViews are delete before they are used again

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#221]
I tried to test the implementation to address #10 and stumbled upon the following error. The task `create_voronoi` depends on the mview `boundaries.vg250_sta_union` which probably got deleted before this task was executed.

The log for reference

```
[2021-04-20 18:55:18,148] {logging_mixin.py:112} INFO - Running <TaskInstance: egon-data-processing-pipeline.create_voronoi 2021-04-20T16:46:38.224785+00:00 [running]> on host RLI-NB-49
[2021-04-20 18:55:18,296] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "boundaries.vg250_sta_union" does not exist
LINE 5:              FROM boundaries.vg250_sta_union a
                          ^

[SQL: 
            INSERT INTO grid.egon_hvmv_substation_voronoi (geom)
            (SELECT ST_Multi(ST_Intersection(
                ST_Transform(a.geometry, 4326), b.geom)) AS geom
             FROM boundaries.vg250_sta_union a
             CROSS JOIN grid.egon_voronoi_no_borders b);
            ]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "boundaries.vg250_sta_union" does not exist
LINE 5:              FROM boundaries.vg250_sta_union a
                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/guido/git/eGon-data/src/egon/data/processing/substation/__init__.py", line 285, in create_voronoi
    """
  File "/home/guido/git/eGon-data/src/egon/data/db.py", line 62, in execute_sql
    con.execute(text(sql_string))
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/guido/miniconda3/envs/eGon-data/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "boundaries.vg250_sta_union" does not exist
LINE 5:              FROM boundaries.vg250_sta_union a
                          ^

[SQL: 
            INSERT INTO grid.egon_hvmv_substation_voronoi (geom)
            (SELECT ST_Multi(ST_Intersection(
                ST_Transform(a.geometry, 4326), b.geom)) AS geom
             FROM boundaries.vg250_sta_union a
             CROSS JOIN grid.egon_voronoi_no_borders b);
            ]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-04-20 18:55:18,300] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=create_voronoi, execution_date=20210420T164638, start_date=20210420T165517, end_date=20210420T165518
[2021-04-20 18:55:22,848] {local_task_job.py:102} INFO - Task exited with return code 1
```

I would like to propose a fix, but I don't have a proper one. It depends on the order of tasks where to place the drop statement for deleting temporary stuff. And the order of execution might change during further development and it might depend of the number of jobs. Maybe the best fix is to delete all temporary tables as final task. Similar as we plan to create table centrally in the beginning of the pipeline. What do you think?

**Comment by gplssm** [comment]
I've switched to the dev branch in between and ran into #226. I installed java system requirements and recreated the database docker container. Afterwards, this issue doesn't occur any more.
