### ISSUE TITLE
Raises psycopg2.errors.OutOfMemory during tasks run_osmtgmod

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#226]
I've experienced an out-of-memory error during eGon-data execution for SH with latest dev branch. Did anyone else had this problem before? 
@ulfmueller do you have an idea?
I'll try it with an increased shared memory size of the docker container.

Some log for reference:
```
...
[2021-04-21 16:49:20,559] {logging_mixin.py:112} WARNING - 04/21/2021 16:49:20 Executing SQL statement 67:
CREATE INDEX all_neighbour_idx ON power_line(all_neighbours)
[2021-04-21 16:49:20,568] {__init__.py:527} INFO - Executing SQL statement 68:
UPDATE power_line SET all_neighbours = otg_get_all_neighbours (id)

[2021-04-21 16:49:20,569] {logging_mixin.py:112} WARNING - 04/21/2021 16:49:20 Executing SQL statement 68:
UPDATE power_line SET all_neighbours = otg_get_all_neighbours (id)
[2021-04-21 16:49:20,572] {__init__.py:527} INFO - Executing SQL statement 69:
ALTER TABLE power_line ADD COLUMN cables_from_neighbour BOOLEAN

[2021-04-21 16:49:20,572] {logging_mixin.py:112} WARNING - 04/21/2021 16:49:20 Executing SQL statement 69:
ALTER TABLE power_line ADD COLUMN cables_from_neighbour BOOLEAN
[2021-04-21 16:49:20,577] {__init__.py:527} INFO - Executing SQL statement 70:
SELECT otg_unknown_value_heuristic ()

[2021-04-21 16:49:20,577] {logging_mixin.py:112} WARNING - 04/21/2021 16:49:20 Executing SQL statement 70:
SELECT otg_unknown_value_heuristic ()
[2021-04-21 16:49:41,395] {__init__.py:538} ERROR - Exception raised with command 70. Check data and code and restart with 'python ego_otg.py egon-data-sh 70'.
Traceback (most recent call last):
  File "/home/guido/git/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 530, in osmtgmod
    cur.execute(command)
psycopg2.errors.OutOfMemory: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
CONTEXT:  SQL statement "CREATE TABLE all_neighbours (
	id BIGINT,
	cables INT,
	frequency INT)"
PL/pgSQL function otg_neighbour_heuristic() line 14 at SQL statement
SQL statement "SELECT otg_neighbour_heuristic ()"
PL/pgSQL function otg_unknown_value_heuristic() line 13 at PERFORM

[2021-04-21 16:49:41,396] {logging_mixin.py:112} WARNING - 04/21/2021 16:49:41 Exception raised with command 70. Check data and code and restart with 'python ego_otg.py egon-data-sh 70'.
Traceback (most recent call last):
  File "/home/guido/git/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 530, in osmtgmod
    cur.execute(command)
psycopg2.errors.OutOfMemory: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
CONTEXT:  SQL statement "CREATE TABLE all_neighbours (
	id BIGINT,
	cables INT,
	frequency INT)"
PL/pgSQL function otg_neighbour_heuristic() line 14 at SQL statement
SQL statement "SELECT otg_neighbour_heuristic ()"
PL/pgSQL function otg_unknown_value_heuristic() line 13 at PERFORM
[2021-04-21 16:49:45,881] {local_task_job.py:102} INFO - Task exited with return code 1
```

I would assume that we might run into bigger out-of-memory errors when this task is executed with the German wide dataset.

**Comment by nesnoj** [comment]
Haha, I just wanted to report the same error:

I deleted the docker container and created everything from scratch again using the latest [dev](https://github.com/openego/eGon-data/tree/2d5bec7adc12f577278405bf9e97732dae71089c) from this morning and the test region only: `egon-data --dataset-boundary Schleswig-Holstein serve` getting the same error reported above.

As recommended in the log, I increased `max_locks_per_transaction` in the psql config inside the docker (from [default of 64](https://www.postgresql.org/docs/12/runtime-config-locks.html) to 1024), restarted the container and voilà, it's at least not crashing immediately (still waiting for completion, though...).

In case this solves the problem, does it make sense to you to change the default `/var/lib/postgresql/data/postgresql.conf` via docker compose to have a higher value? @gnn

**Comment by ClaraBuettner** [comment]
It looks very similar to #206 which could be solved by installing missing pre-requisites. Have you checked this?

**Comment by gplssm** [comment]
Thanks for the hint! That solved it for me :+1:

**Comment by nesnoj** [comment]
Works out here too, thanks @ClaraBuettner .
But how the heck are transaction locks related to java?? :confused:
Ah, got it, one of those days full of
```
 _______
< magic >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
