### ISSUE TITLE
Table openstreetmap.osm_deu_nodes is missing in ehv_substation_extraction

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#236]
While running the workflow for "Everything" on `features/#228-make-database-data-storage-location-configurable` (5160d971ba887b01f9fdd81460d14c19ed1a1f42) (very close to dev, just the location of the docker container has changed) the task `ehv_substation_extraction` couldn't find the table openstreetmap.osm_deu_nodes is missing.

```
...
DROP VIEW IF EXISTS grid.egon_node_substations_with_hoes CASCADE;
DROP VIEW IF EXISTS grid.egon_way_substations_with_hoes CASCADE;
DROP VIEW IF EXISTS grid.egon_way_substations CASCADE;
[2021-04-28 23:04:49,779] {taskinstance.py:1150} ERROR - relation "openstreetmap.osm_deu_nodes" does not exist
LINE 3:                    FROM openstreetmap.osm_deu_nodes
                                ^
QUERY:  SELECT (SELECT ST_SetSRID
                   (ST_MakePoint((max(lon) + min(lon))/200.0,(max(lat) + min(lat))/200.0),900913)
                   FROM openstreetmap.osm_deu_nodes
                   WHERE id in (SELECT unnest(nodes)
                     FROM openstreetmap.osm_deu_ways
                     WHERE id in (SELECT trim(leading 'w' from member)::bigint
			                     FROM (SELECT unnest(members) as member) t
	                               WHERE member~E'[w,1,2,3,4,5,6,7,8,9,0]')))
CONTEXT:  PL/pgSQL function relation_geometry(text[]) line 5 at assignment
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/local/RL-INSTITUT/guido.plessmann/miniconda3/envs/eGon-data/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.UndefinedTable: relation "openstreetmap.osm_deu_nodes" does not exist
LINE 3:                    FROM openstreetmap.osm_deu_nodes
                                ^
QUERY:  SELECT (SELECT ST_SetSRID
                   (ST_MakePoint((max(lon) + min(lon))/200.0,(max(lat) + min(lat))/200.0),900913)
                   FROM openstreetmap.osm_deu_nodes
                   WHERE id in (SELECT unnest(nodes)
                     FROM openstreetmap.osm_deu_ways
                     WHERE id in (SELECT trim(leading 'w' from member)::bigint
			                     FROM (SELECT unnest(members) as member) t
	                               WHERE member~E'[w,1,2,3,4,5,6,7,8,9,0]')))
CONTEXT:  PL/pgSQL function relation_geometry(text[]) line 5 at assignment

[2021-04-28 23:04:49,781] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=ehv_substation_extraction, execution_date=20210428T062221, start_date=20210428T230444, end_date=20210428T230449
[2021-04-28 23:04:54,016] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ClaraBuettner** [comment]
I run into the same error on dev branch

**Comment by IlkaCu** [comment]
I removed the wrong table name from a sql function used in the table extraction (2a1c4ef73473c02a8054f9d370c094964abd76cf)
This makes the processing step executable but creates some interesting results close to Offenburg:
![grafik](https://user-images.githubusercontent.com/16799094/116986995-ca2b2e00-acce-11eb-9e27-aaaf71065a3f.png)
These substations are represented by point geometries in the polygon column in `grid.egon_ehv_substation`
I will dig a bit deeper and try to find out why this happens.
