### ISSUE TITLE
otg_connect_busses_to_lines_1: wrong geometry types

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#241]
As @ClaraBuettner reported in #238 osmTgmod throws the following error when executing it with the most recent OSM data set and the code from branch `fixes/#236-missing-osm_deu_nodes`

This is what @ClaraBuettner posted: 

It solves the problem described in #236  but I run into errors in osmtgmod: 

```

> [2021-04-29 16:23:34,735] {logging_mixin.py:120} WARNING - 04/29/2021 16:23:34 Executing SQL statement 201:
> CREATE TRIGGER problem_log_trigger
> AFTER DELETE ON power_line_sep
> FOR EACH ROW 
> EXECUTE PROCEDURE otg_power_line_as_branch_problem_tg ('dead_end')
> [2021-04-29 16:23:34,748] {__init__.py:526} INFO - Executing SQL statement 202:
> SELECT otg_connect_busses_to_lines_1 ()
> 
> [2021-04-29 16:23:34,748] {logging_mixin.py:120} WARNING - 04/29/2021 16:23:34 Executing SQL statement 202:
> SELECT otg_connect_busses_to_lines_1 ()
> [2021-04-29 16:29:52,437] {__init__.py:533} ERROR - Exception raised with command 202. Check data and code and restart with 'python ego_otg.py egon-data-clara 202'.
> Traceback (most recent call last):
>   File "/home/buettner/egon-data/git/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 530, in osmtgmod
>     cur.execute(command)
> psycopg2.errors.InvalidParameterValue: Geometry type (Point) does not match column type (LineString)
> CONTEXT:  PL/pgSQL function otg_connect_busses_to_lines_1() line 81 at assignment
> 
> [2021-04-29 16:29:52,446] {logging_mixin.py:120} WARNING - 04/29/2021 16:29:52 Exception raised with command 202. Check data and code and restart with 'python ego_otg.py egon-data-clara 202'.
> Traceback (most recent call last):
>   File "/home/buettner/egon-data/git/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 530, in osmtgmod
>     cur.execute(command)
> psycopg2.errors.InvalidParameterValue: Geometry type (Point) does not match column type (LineString)
> CONTEXT:  PL/pgSQL function otg_connect_busses_to_lines_1() line 81 at assignment
> [2021-04-29 16:29:57,297] {local_task_job.py:102} INFO - Task exited with return code 1

```

**Comment by ClaraBuettner** [comment]
The problem is caused by a new 110/380kV substation in osm (https://www.openstreetmap.org/way/766922101). This one is not listed in our ehv substations, but the one very close to it (Garenfeld) is a ehv_substation. 
This is the result using osm data from 2021:
![Garenfeld_osm2021](https://user-images.githubusercontent.com/22964326/117107338-b55ba280-ad81-11eb-8590-3c86777e69e2.png)
This is the result using osm data from 2020:
![Garenfeld_osm_2020](https://user-images.githubusercontent.com/22964326/117107342-b68ccf80-ad81-11eb-932d-85e95fa9629a.png)
I'm wondering why the new substation is not part of our ehv substations. @IlkaCu Is there a buffer and the next substation might be too close to identify this as a new substation?
