### ISSUE TITLE
Migrate datasets to versioning module

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#297]
Migrating the following datasets of #277 to the versioning module:

- [x] mv grid districts
- [x] re potential areas
- [x] retrieve MaStR data
- [ ] task dependency error fix needed #298 
- [x] rename re potential areas functions to be more specific in graph view

**Comment by nailend** [comment]
Implementing the versioning for mv_grid_district  directly using the Dataset class in pipeline.py ends up in the same task error already mentioned in https://github.com/openego/eGon-data/pull/260#issuecomment-864936520. This happens after finishing the last task of the Dataset.


```*** Reading local file: /home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/egon-data-sh/airflow/logs/egon-data-processing-pipeline/define_mv_grid_districts/2021-06-22T09:33:02.407922+00:00/1.log
[2021-06-22 11:42:42,294] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.define_mv_grid_districts 2021-06-22T09:33:02.407922+00:00 [queued]>
[2021-06-22 11:42:42,371] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.define_mv_grid_districts 2021-06-22T09:33:02.407922+00:00 [queued]>
[2021-06-22 11:42:42,371] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 11:42:42,371] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-06-22 11:42:42,371] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 11:42:42,389] {taskinstance.py:901} INFO - Executing <Task(MV_grid_districts (versioned)): define_mv_grid_districts> on 2021-06-22T09:33:02.407922+00:00
[2021-06-22 11:42:42,396] {standard_task_runner.py:54} INFO - Started process 809282 to run task
[2021-06-22 11:42:42,449] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'define_mv_grid_districts', '2021-06-22T09:33:02.407922+00:00', '--job_id', '54', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp6r72521x']
[2021-06-22 11:42:42,450] {standard_task_runner.py:78} INFO - Job 54: Subtask define_mv_grid_districts
[2021-06-22 11:42:42,510] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.define_mv_grid_districts 2021-06-22T09:33:02.407922+00:00 [running]> on host rli-nb-74lin.rl-institut.local
[2021-06-22 11:42:54,563] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-22 11:42:54,564] {taskinstance.py:1150} ERROR - 'PostgresOperator' object has no attribute 'dataset'
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/egon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 191, in skip_task
    function(session)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 202, in update
    [
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 206, in <listcomp>
    dependency.dataset
AttributeError: 'PostgresOperator' object has no attribute 'dataset'
[2021-06-22 11:42:54,566] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=define_mv_grid_districts, execution_date=20210622T093302, start_date=20210622T094242, end_date=20210622T094254
[2021-06-22 11:42:57,268] {local_task_job.py:102} INFO - Task exited with return code 1```
