### ISSUE TITLE
Airflow task error after implementing versioning

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#298]
The following task error pops up after implementing versioning for the mv_gird_districts-Dataset. Similiar to https://github.com/openego/eGon-data/issues/297#issuecomment-865904336 and https://github.com/openego/eGon-data/pull/260#issuecomment-864936520
I assume all tasks in the dataset are actually completed but finish with an error anyways. Therefore no further depending task can be executed. 

```*** Reading local file: /home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/egon-data-sh/airflow/logs/egon-data-processing-pipeline/define-mv-grid-districts/2021-06-22T13:47:39.582736+00:00/1.log
[2021-06-22 15:57:42,529] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.define-mv-grid-districts 2021-06-22T13:47:39.582736+00:00 [queued]>
[2021-06-22 15:57:42,593] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.define-mv-grid-districts 2021-06-22T13:47:39.582736+00:00 [queued]>
[2021-06-22 15:57:42,594] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 15:57:42,594] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-06-22 15:57:42,594] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 15:57:42,616] {taskinstance.py:901} INFO - Executing <Task(MV_grid_districts (versioned)): define-mv-grid-districts> on 2021-06-22T13:47:39.582736+00:00
[2021-06-22 15:57:42,625] {standard_task_runner.py:54} INFO - Started process 867185 to run task
[2021-06-22 15:57:42,685] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'define-mv-grid-districts', '2021-06-22T13:47:39.582736+00:00', '--job_id', '55', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp4p5o2ibd']
[2021-06-22 15:57:42,686] {standard_task_runner.py:78} INFO - Job 55: Subtask define-mv-grid-districts
[2021-06-22 15:57:42,740] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.define-mv-grid-districts 2021-06-22T13:47:39.582736+00:00 [running]> on host rli-nb-74lin.rl-institut.local
[2021-06-22 15:57:55,015] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-22 15:57:55,018] {taskinstance.py:1150} ERROR - 'PostgresOperator' object has no attribute 'dataset'
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/egon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 191, in skip_task
    function(session)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 202, in update
    [
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 206, in <listcomp>
    dependency.dataset
AttributeError: 'PostgresOperator' object has no attribute 'dataset'
[2021-06-22 15:57:55,020] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=define-mv-grid-districts, execution_date=20210622T134739, start_date=20210622T135742, end_date=20210622T135755
[2021-06-22 15:57:57,483] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by gnn** [comment]
The commit(s) on [features/#298-allow-unversioned-tasks-as-dataset-dependencies](openego/eGon-data/tree/features/%23298-allow-unversioned-tasks-as-dataset-dependencies) should fix this issue. Would it be possible for you to test that? Just merge the branch into your failing branches locally and see whether your issue gets fixed. If so, I'll make a PR and merge the branch into dev.

**Comment by nailend** [comment]
@gnn tested your fix! Works perfectly! Thx
