### ISSUE TITLE
Migrate osmTGmod to datasets

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGon-data#305]

**Comment by ulfmueller** [comment]
My migration does not work - and I do not understand why. It is on this [branch](https://github.com/openego/eGon-data/tree/features/%23305-migrate-osmTGmod)

The following error occurs:
```
ERROR [airflow.models.dagbag.DagBag] Failed to import: /home/ulf/github/eGon-data/src/egon/data/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/ulf/venvs/egondata/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ulf/github/eGon-data/src/egon/data/airflow/dags/pipeline.py", line 326, in <module>
    osmtgmod_pypsa = tasks["osmtgmod.to_pypsa"]
KeyError: 'osmtgmod.to_pypsa'

```
Any ideas?

**Comment by ulfmueller** [comment]
thx @gnn 94907199d04240c9996514e0303684ae545c8865 seems to work... may be s. th. for some 'do's and don'ts'?!

**Comment by ClaraBuettner** [comment]
@ulfmueller Do you know if there are still open todos in this branch?

**Comment by ulfmueller** [comment]
it should be finished. Check out the corresponding PR: #374
