### ISSUE TITLE
Weather data download fails 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#312]
The task download-weather-data fails when the data has to be downloaded as @AmeliaNadal mentioned. Since the data is only downloaded once, the error occurs only if the tasks did not run before. 
```

> [2021-06-30 11:22:10,407] {api.py:517} INFO - Welcome to the CDS
> [2021-06-30 11:22:10,407] {api.py:517} INFO - Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels
> [2021-06-30 11:22:10,488] {api.py:517} INFO - Request is queued
> [2021-06-30 11:22:11,544] {api.py:517} INFO - Request is failed
> [2021-06-30 11:22:11,544] {api.py:529} ERROR - Message: no data is available within your requested subset
> [2021-06-30 11:22:11,544] {api.py:529} ERROR - Reason:  Request returned no data
> [2021-06-30 11:22:11,544] {api.py:529} ERROR -   Traceback (most recent call last):
> [2021-06-30 11:22:11,544] {api.py:529} ERROR -     File "/opt/cdstoolbox/cdscompute/cdscompute/cdshandlers/services/handler.py", line 55, in handle_request
> [2021-06-30 11:22:11,544] {api.py:529} ERROR -       result = cached(context.method, proc, context, context.args, context.kwargs)
> [2021-06-30 11:22:11,544] {api.py:529} ERROR -     File "/opt/cdstoolbox/cdscompute/cdscompute/caching.py", line 108, in cached
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -       result = proc(context, *context.args, **context.kwargs)
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -     File "/opt/cdstoolbox/cdscompute/cdscompute/services.py", line 118, in __call__
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -       return p(*args, **kwargs)
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -     File "/opt/cdstoolbox/cdscompute/cdscompute/services.py", line 59, in __call__
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -       return self.proc(context, *args, **kwargs)
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -     File "/home/cds/cdsservices/services/mars/mars.py", line 45, in internal
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -       return mars(context, request, **kwargs)
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -     File "/home/cds/cdsservices/services/mars/mars.py", line 17, in mars
> [2021-06-30 11:22:11,545] {api.py:529} ERROR -       execute_mars(context, requests)
> [2021-06-30 11:22:11,546] {api.py:529} ERROR -     File "/home/cds/cdsservices/services/mars/execute_mars.py", line 25, in execute_mars
> [2021-06-30 11:22:11,546] {api.py:529} ERROR -       raise NoDataException("Request returned no data", '')
> [2021-06-30 11:22:11,546] {api.py:529} ERROR -   cdsinf.exceptions.NoDataException: Request returned no data
> [2021-06-30 11:22:11,546] {taskinstance.py:1150} ERROR - no data is available within your requested subset. Request returned no data.
> Traceback (most recent call last):

```
This seems to be caused by a change in the CDS database, they renamed one variable (see https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation) but our version of atlite (which downloads the weather data) still uses the old name.
I will check if we can solve this in eGon-data (maybe we don't need this variable) otherwise we have to update our atlite version which might conflict pypsa-eur-sec.

**Comment by nesnoj** [comment]
Same here :(

**Comment by nesnoj** [comment]
BTW: A manual upgrade to latest version of atlite did not work as atlite's internal format has changed and requires some manual conversion. So I'll wait for your fix @ClaraBuettner, you're quite more into the internals here..
