### ISSUE TITLE
Task insert-gas-grid fails

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#319]
I ran everything from scratch using today's dev, the task `insert-gas-grid` fails.
Am I the only one / are you aware of this @AmeliaNadal ?

Log:
```
[2021-07-08 10:05:02,273] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): insert-gas-grid> on 2021-07-07T11:43:08.774454+00:00
[2021-07-08 10:05:02,282] {standard_task_runner.py:54} INFO - Started process 454116 to run task
[2021-07-08 10:05:02,352] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'insert-gas-grid', '2021-07-07T11:43:08.774454+00:00', '--job_id', '61', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpplijg7ke']
[2021-07-08 10:05:02,352] {standard_task_runner.py:78} INFO - Job 61: Subtask insert-gas-grid
[2021-07-08 10:05:02,388] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.insert-gas-grid 2021-07-07T11:43:08.774454+00:00 [running]> on host nesnoj-nb
[2021-07-08 10:05:40,569] {taskinstance.py:1150} ERROR - (psycopg2.errors.SyntaxError) syntax error at or near "{"
LINE 2:         SELECT MAX({component}_id) FROM grid.egon_pf_hv_{com...
                           ^

[SQL: 
        SELECT MAX({component}_id) FROM grid.egon_pf_hv_{component}
        ]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "{"
LINE 2:         SELECT MAX({component}_id) FROM grid.egon_pf_hv_{com...
                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/egon/data/importing/gas_grid/__init__.py", line 328, in insert_gas_data
    gas_nodes_list = define_gas_nodes_list()
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/egon/data/importing/gas_grid/__init__.py", line 77, in define_gas_nodes_list
    new_id = next_id('bus')
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/egon/data/importing/gas_grid/__init__.py", line 31, in next_id
    max_id = db.select_dataframe(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/egon/data/db.py", line 157, in select_dataframe
    df = pd.read_sql(sql, engine(), index_col=index_col)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/sql.py", line 521, in read_sql
    return pandas_sql.read_query(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/sql.py", line 1308, in read_query
    result = self.execute(*args)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/sql.py", line 1176, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "{"
LINE 2:         SELECT MAX({component}_id) FROM grid.egon_pf_hv_{com...
                           ^

[SQL: 
        SELECT MAX({component}_id) FROM grid.egon_pf_hv_{component}
        ]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-07-08 10:05:40,572] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=insert-gas-grid, execution_date=20210707T114308, start_date=20210708T080502, end_date=20210708T080540
[2021-07-08 10:05:42,257] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by nesnoj** [comment]
(region: SH only)

**Comment by nesnoj** [comment]
Hold on, it's only failing on my local machine but it works out on our server.. o_O

I got the impression that several tasks are quite sensitive to the environment they're running in, experiencing this again and again.. I'll get back to you when I found the reason for your task.

**Comment by AmeliaNadal** [comment]
@nesnoj I accidentally merge into dev some code that was failing (I forgot the "f" preceding the """ in these lines https://github.com/openego/eGon-data/blob/783b7a78de0c6e94bf945ac56097cdf09118c19f/src/egon/data/importing/gas_grid/__init__.py#L31-L34) but this has been fixed (also in dev branch).
Could you maybe check that the f is there in your local version of the code?

**Comment by nesnoj** [comment]
With another reinstall it's working out.
It is strange because the f-String was already fixed before when it failed... 
I won't dig any deeper, thx! :)
