### ISSUE TITLE
Task insert-nep-data fails

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#322]
I ran everything from scratch (on 2 different systems with new px3.8 venv) using current dev and SH region.
The task `insert-nep-data` fails.

Log:
```
[2021-07-09 00:07:40,140] {taskinstance.py:1150} ERROR - 'Schleswig-Holstein'
Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Schleswig-Holstein'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nesnoj/git-repos/openego/eGon-data/src/egon/data/importing/nep_input_data/__init__.py", line 341, in insert_data_nep
    insert_capacities_per_federal_state_nep()
  File "/home/nesnoj/git-repos/openego/eGon-data/src/egon/data/importing/nep_input_data/__init__.py", line 173, in insert_capacities_per_federal_state_nep
    data.loc[data.carrier == 'residential_rural_heat_pump', bl] *= 3e-6
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/generic.py", line 3758, in xs
    return self[key]
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Schleswig-Holstein'
[2021-07-09 00:07:40,152] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=insert-nep-data, execution_date=20210708T211548, start_date=20210708T220739, end_date=20210708T220740
[2021-07-09 00:07:44,407] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by nesnoj** [comment]
Same error with my instance on your server..

**Comment by nesnoj** [comment]
Code:

https://github.com/openego/eGon-data/blob/13e390376acefb1a7576ba50fe310a4f9aa2db7f/src/egon/data/importing/nep_input_data/__init__.py#L155-L176

In L173 it tries to access the index value "Schleswig-Holstein" but it does not exist due to the reset_index in L165. This cannot work. The DF `data` looks like this when reaching L173:

```
                         carrier  component      country nuts scenario_name
0                       biomass  generator  Deutschland  DEF      eGon2035
1                           gas  generator  Deutschland  DEF      eGon2035
2                           oil  generator  Deutschland  DEF      eGon2035
3                  pumped_hydro  generator  Deutschland  DEF      eGon2035
4                     reservoir  generator  Deutschland  DEF      eGon2035
5   residential_rural_heat_pump  generator  Deutschland  DEF      eGon2035
6                  run_of_river  generator  Deutschland  DEF      eGon2035
7                     small_chp  generator  Deutschland  DEF      eGon2035
8                         solar  generator  Deutschland  DEF      eGon2035
9                 solar_rooftop  generator  Deutschland  DEF      eGon2035
10                wind_offshore  generator  Deutschland  DEF      eGon2035
11                 wind_onshore  generator  Deutschland  DEF      eGon2035
```
How's this supposed to have worked before?
With your new instance used in #258 this task ran successfully at your end? @ClaraBuettner

**Comment by nesnoj** [comment]
Similar result with new instance on your server: `KeyError: 'Baden-Württemberg'`
Maybe a problem with an upstream task?

**Comment by ClaraBuettner** [comment]
This seems to be related to the pandas version. On my current installation I have` pandas==1.2.4` and my DF data looks like this when reaching L173: 
```

                                            Schleswig-Holstein  ... scenario_name
Braunkohle                                                   0  ...      eGon2035
Erdgas                                                     0.6  ...      eGon2035
Kuppelgas                                                    0  ...      eGon2035
Oel                                                          0  ...      eGon2035
Abfall                                                       0  ...      eGon2035
sonstige Konventionelle                                    0.1  ...      eGon2035
KWK < 10 MW                                                0.3  ...      eGon2035
Pumpspeicher                                               0.1  ...      eGon2035
Lauf- und Speicherwasser                                     0  ...      eGon2035
Wind onshore                                              12.1  ...      eGon2035
Wind offshore                                                7  ...      eGon2035
Photovoltaik                                               4.3  ...      eGon2035
Biomasse                                                   0.6  ...      eGon2035
sonstige EE                                                  0  ...      eGon2035
Band des Stromverbrauchs (ungleichzeitig)**                1-3  ...      eGon2035
zusaetzliche Verbraucher DSM                               0.2  ...      eGon2035
zusaetzliche Verbraucher PtH                               0.1  ...      eGon2035
zusaetzliche Verbraucher PtG                               0.5  ...      eGon2035
Haushaltswaermepumpen                            330873.666667  ...      eGon2035
Elektromobilitaet gesamt                         502704.608187  ...      eGon2035
Verbrauch Haushaltswaermepumpen                       0.706922  ...      eGon2035
Verbrauch Elektromobilitaet                            1.73785  ...      eGon2035
PV (Aufdach)                                          2.699922  ...      eGon2035
PV (Freiflaeche)                                      1.337984  ...      eGon2035
Laufwasser                                                 NaN  ...      eGon2035
Speicherwasser                                             NaN  ...      eGon2035

```
But when I update pandas to the most recent version (1.3.0) , I can reproduce your error and the DF looks like this: 
```
                        carrier  component      country nuts scenario_name
0                       biomass  generator  Deutschland  DEF      eGon2035
1                           gas  generator  Deutschland  DEF      eGon2035
2                           oil  generator  Deutschland  DEF      eGon2035
3                  pumped_hydro  generator  Deutschland  DEF      eGon2035
4                     reservoir  generator  Deutschland  DEF      eGon2035
5   residential_rural_heat_pump  generator  Deutschland  DEF      eGon2035
6                  run_of_river  generator  Deutschland  DEF      eGon2035
7                     small_chp  generator  Deutschland  DEF      eGon2035
8                         solar  generator  Deutschland  DEF      eGon2035
9                 solar_rooftop  generator  Deutschland  DEF      eGon2035
10                wind_offshore  generator  Deutschland  DEF      eGon2035
11                 wind_onshore  generator  Deutschland  DEF      eGon2035
```
So the 'Schleswig-Holstein' column is missing when I use the newest pandas version. This seems to happen due to a change in the aggregation methods in pandas. When I update line 165 to `data = data.groupby(data.carrier).sum(numeric_only=False).reset_index()` it is working again in all versions of pandas. 
I will prepare a PR.

**Comment by nesnoj** [comment]
Thank you.
Will check.
General issue on this: #343
