### ISSUE TITLE
Import error:  cannot import name 'resolve_types'

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#37]
When starting egon-data with `egon-data serve` the following error occurs: 

```
Traceback (most recent call last):
  File "/home/ilka/.local/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/home/ilka/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 94, in <module>
    api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ilka/.local/lib/python3.6/site-packages/airflow/api/client/local_client.py", line 24, in <module>
    from airflow.api.common.experimental import delete_dag
  File "/home/ilka/.local/lib/python3.6/site-packages/airflow/api/common/experimental/delete_dag.py", line 26, in <module>
    from airflow.models.serialized_dag import SerializedDagModel
  File "/home/ilka/.local/lib/python3.6/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
    from airflow.serialization.serialized_objects import SerializedDAG
  File "/home/ilka/.local/lib/python3.6/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
    import cattr
  File "/home/ilka/.local/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/home/ilka/.local/lib/python3.6/site-packages/cattr/converters.py", line 16, in <module>
    from attr import fields, resolve_types
ImportError: cannot import name 'resolve_types'

```
Can you help?

**Comment by gnn** [comment]
Could you please post the output of `pip list | grep attr`?

**Comment by AmeliaNadal** [comment]
attrs                  19.3.0
cattrs                 1.0.0

**Comment by IlkaCu** [comment]
attrs (20.1.0)
cattrs (1.1.0)

**Comment by gnn** [comment]
Huh? Somebody deleted my previous comment.
Anyway, that means `pip` didn't resolve dependency constraints correctly. In order to fix this, it's probably best to uninstall `egon.data` and reinstall it using `pip install --use-feature=2020-resolver`, @IlkaCu.

**Comment by IlkaCu** [comment]
This solved my problem, but I had to upgrade pip before I was able to install egon.data the way you suggested above. 
Thanks a lot!
