### ISSUE TITLE
Task `insert-data-nep` fails due to missing xlrd but package is installed

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#400]
Yesterday I installed everything from scratch incl. a fresh venv and ran the testmode. I'm getting:

```
[2021-08-18 16:22:32,861] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T15:58:04.062222+00:00 [queued]>
[2021-08-18 16:22:32,969] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T15:58:04.062222+00:00 [queued]>
[2021-08-18 16:22:32,969] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 16:22:32,969] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-08-18 16:22:32,969] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 16:22:33,059] {taskinstance.py:901} INFO - Executing <Task(ScenarioCapacities (versioned)): scenario_capacities.insert-data-nep> on 2021-08-18T15:58:04.062222+00:00
[2021-08-18 16:22:33,066] {standard_task_runner.py:54} INFO - Started process 2749 to run task
[2021-08-18 16:22:33,262] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'scenario_capacities.insert-data-nep', '2021-08-18T15:58:04.062222+00:00', '--job_id', '54', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpnf77ne_7']
[2021-08-18 16:22:33,263] {standard_task_runner.py:78} INFO - Job 54: Subtask scenario_capacities.insert-data-nep
[2021-08-18 16:22:33,446] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T15:58:04.062222+00:00 [running]> on host srvsim01.rl-institut.local
[2021-08-18 16:22:34,021] {taskinstance.py:1150} ERROR - Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/__init__.py", line 192, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/scenario_capacities.py", line 356, in insert_data_nep
    insert_capacities_per_federal_state_nep()
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/scenario_capacities.py", line 125, in insert_capacities_per_federal_state_nep
    df = pd.read_excel(target_file, sheet_name='1.Entwurf_NEP2035_V2021',
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1140, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 24, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/compat/_optional.py", line 109, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2021-08-18 16:22:34,034] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=scenario_capacities.insert-data-nep, execution_date=20210818T155804, start_date=20210818T162232, end_date=20210818T162234
[2021-08-18 16:22:37,756] {local_task_job.py:102} INFO - Task exited with return code 1
```

But xlrd 2.0.1 is installed.
Full package stack: 
[pip_freeze.txt](https://github.com/openego/eGon-data/files/7012352/pip_freeze.txt)

Did anybody else encounter this problem? Maybe you, @ClaraBuettner ? ;)

**Comment by AmeliaNadal** [comment]
I am getting another error message for the same task:

```
[2021-08-18 17:20:38,506] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T14:46:22.818131+00:00 [queued]>
[2021-08-18 17:20:38,654] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T14:46:22.818131+00:00 [queued]>
[2021-08-18 17:20:38,654] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 17:20:38,654] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-08-18 17:20:38,654] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 17:20:38,701] {taskinstance.py:901} INFO - Executing <Task(ScenarioCapacities (versioned)): scenario_capacities.insert-data-nep> on 2021-08-18T14:46:22.818131+00:00
[2021-08-18 17:20:38,709] {standard_task_runner.py:54} INFO - Started process 18511 to run task
[2021-08-18 17:20:38,784] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'scenario_capacities.insert-data-nep', '2021-08-18T14:46:22.818131+00:00', '--job_id', '2793', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp6gvuvre9']
[2021-08-18 17:20:38,785] {standard_task_runner.py:78} INFO - Job 2793: Subtask scenario_capacities.insert-data-nep
[2021-08-18 17:20:38,909] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.scenario_capacities.insert-data-nep 2021-08-18T14:46:22.818131+00:00 [running]> on host torch.esy.ve.dlr
[2021-08-18 17:20:39,961] {taskinstance.py:1150} ERROR - 'Schleswig-Holstein'
Traceback (most recent call last):
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Schleswig-Holstein'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/__init__.py", line 192, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/scenario_capacities.py", line 355, in insert_data_nep
    insert_capacities_per_federal_state_nep()
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/scenario_capacities.py", line 187, in insert_capacities_per_federal_state_nep
    data.loc[data.carrier == 'residential_rural_heat_pump', bl] *= 3e-6
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/generic.py", line 3758, in xs
    return self[key]
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Schleswig-Holstein'
[2021-08-18 17:20:39,974] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=scenario_capacities.insert-data-nep, execution_date=20210818T144622, start_date=20210818T152038, end_date=20210818T152039
[2021-08-18 17:20:43,297] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by nesnoj** [comment]
> I am getting another error message for the same task:

@AmeliaNadal Sound like #322. Are you using the latest dev from yesterday? Because the fix #342 was just merged..

**Comment by AmeliaNadal** [comment]
Thanks for the advise, the problem was solved by using pandas version 1.2.4.

**Comment by ClaraBuettner** [comment]
> But xlrd 2.0.1 is installed.
> Full package stack:
> [pip_freeze.txt](https://github.com/openego/eGon-data/files/7012352/pip_freeze.txt)
> 
> Did anybody else encounter this problem? Maybe you, @ClaraBuettner ? ;)

I did not see this before and also tested it again several times in different environments but couldn't reproduce this error... But some packages (e.g. demandregios disaggregator which also uses xlrd) are installed in a run of egon-data. So I'm wondering if xlrd might be only installed via the disaggregator installation, and is therefore missing when` insert-nep data `is executed before the disaggregator is installed. I will check this.

**Comment by ClaraBuettner** [comment]
Yes, xlrd is not part of the egon-data installation and only installed with the disaggregator tool. I could either add xlrd to the setup.py of egon-data or set a dependency from insert-nep-data to the disaggregator installation. 
I think I would prefer the first option in case other tasks also use this package. If your ok with this, I will create a branch and PR.

**Comment by nesnoj** [comment]
Yes the 1st one sounds better to me too, this should be definitely done - thanks!
But as xlrd is part of my installation I'd expect it to run successful at least when I retrigger the task, but I'm keep getting the same error o_O.

**Comment by ClaraBuettner** [comment]
> Yes the 1st one sounds better to me too, this should be definitely done - thanks!
> But as xlrd is part of my installation now I'd expect it to run successful at least when I retrigger the task, but I keep getting the same error o_O.

That's very strange, when the task is cleared it should definitely work...

**Comment by nesnoj** [comment]
After retriggering it again it worked out, I'll give it another clean run try when reviewing #404.
