### ISSUE TITLE
Task `heat_demand.scenario-data-import` fails due to missing file raster2pgsql

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#401]
Yesterday I installed everything from scratch incl. a fresh venv and ran the testmode. I'm getting:

```
[2021-08-18 16:16:22,167] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.heat_demand.scenario-data-import 2021-08-18T15:58:04.062222+00:00 [queued]>
[2021-08-18 16:16:22,284] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.heat_demand.scenario-data-import 2021-08-18T15:58:04.062222+00:00 [queued]>
[2021-08-18 16:16:22,285] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 16:16:22,285] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-08-18 16:16:22,285] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-08-18 16:16:23,266] {taskinstance.py:901} INFO - Executing <Task(Heat-demands (versioned)): heat_demand.scenario-data-import> on 2021-08-18T15:58:04.062222+00:00
[2021-08-18 16:16:23,272] {standard_task_runner.py:54} INFO - Started process 21959 to run task
[2021-08-18 16:16:23,338] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'heat_demand.scenario-data-import', '2021-08-18T15:58:04.062222+00:00', '--job_id', '43', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpdk_ox9u9']
[2021-08-18 16:16:23,339] {standard_task_runner.py:78} INFO - Job 43: Subtask heat_demand.scenario-data-import
[2021-08-18 16:16:24,325] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.heat_demand.scenario-data-import 2021-08-18T15:58:04.062222+00:00 [running]> on host srvsim01.rl-institut.local
[2021-08-18 16:17:31,463] {taskinstance.py:1150} ERROR - [Errno 2] No such file or directory: 'raster2pgsql'
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/__init__.py", line 192, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/heat_demand/__init__.py", line 840, in scenario_data_import
    heat_demand_to_db_table()
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/heat_demand/__init__.py", line 471, in heat_demand_to_db_table
    import_rasters = subprocess.run(
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/subprocess.py", line 58, in run
    result = subprocess.run(*args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'raster2pgsql'
[2021-08-18 16:17:31,468] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=heat_demand.scenario-data-import, execution_date=20210818T155804, start_date=20210818T161622, end_date=20210818T161731
[2021-08-18 16:17:34,980] {local_task_job.py:102} INFO - Task exited with return code 1
```

Could this be related to your recent migration #313 @ClaraBuettner ?

**Comment by nesnoj** [comment]
`raster2pgsql` seems to be part of postGIS, it seems to be activated here:
https://github.com/openego/eGon-data/blob/637a7d3a2a57b2dcb612f4e91768abffb5e7f9e9/src/egon/data/datasets/database.py#L7-L12
I tried to make sure it's activated by recreating the extension with `CREATE EXTENSION postgis_raster;` but it already was, so the problem must lie elsewhere..

**Comment by ClaraBuettner** [comment]
I think this is not related to the migration.  'raster2pgsql' is not a a file but a command of the postgis tool. Did you checked if  postgis is installed as described in the pre-requisites?

**Comment by nesnoj** [comment]
> I think this is not related to the migration. 'raster2pgsql' is not a a file but a command of the postgis tool. Did you checked if postgis is installed as described in the pre-requisites?

Yepp, see [above](https://github.com/openego/eGon-data/issues/401#issuecomment-901673850)

**Comment by nesnoj** [comment]
Ah, wait, gimme a sec

**Comment by nesnoj** [comment]
Seems that my postgis install has been undermined  : /
