### ISSUE TITLE
Task "osmtgmod.import-osm-data " fails

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eGon-data#424]
The task osmtgmod.import-osm-data fails using the test case on my local machine. There was a similar issue (#344), but it did not help in this case. 
```
[2021-09-02 12:50:01,506] {taskinstance.py:901} INFO - Executing <Task(Osmtgmod (versioned)): osmtgmod.import-osm-data> on 2021-09-02T10:37:12.489233+00:00
[2021-09-02 12:50:01,511] {standard_task_runner.py:54} INFO - Started process 26609 to run task
[2021-09-02 12:50:01,562] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'osmtgmod.import-osm-data', '2021-09-02T10:37:12.489233+00:00', '--job_id', '706', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpvpjix6ag']
[2021-09-02 12:50:01,563] {standard_task_runner.py:78} INFO - Job 706: Subtask osmtgmod.import-osm-data
[2021-09-02 12:50:01,596] {logging_mixin.py:112} INFO - Running <TaskInstance: egon-data-processing-pipeline.osmtgmod.import-osm-data 2021-09-02T10:37:12.489233+00:00 [running]> on host student-pc
[2021-09-02 12:50:17,622] {__init__.py:90} INFO - Creating status table ...
[2021-09-02 12:50:17,638] {__init__.py:99} INFO - Status table created.
[2021-09-02 12:50:17,638] {__init__.py:103} INFO - Dropping osmtgmod_results schema if exists
[2021-09-02 12:50:17,649] {__init__.py:106} INFO - Loading functions and result schema ...
[2021-09-02 12:50:17,649] {__init__.py:115} INFO - Running script sql-scripts/extensions.sql ...
[2021-09-02 12:50:17,781] {__init__.py:121} INFO - Done.
[2021-09-02 12:50:17,781] {__init__.py:115} INFO - Running script sql-scripts/functions.sql ...
[2021-09-02 12:50:17,854] {__init__.py:121} INFO - Done.
[2021-09-02 12:50:17,854] {__init__.py:115} INFO - Running script sql-scripts/admin_boundaries.sql ...
[2021-09-02 12:50:24,763] {__init__.py:121} INFO - Done.
[2021-09-02 12:50:24,763] {__init__.py:115} INFO - Running script sql-scripts/electrical_properties.sql ...
[2021-09-02 12:50:24,812] {__init__.py:121} INFO - Done.
[2021-09-02 12:50:24,812] {__init__.py:115} INFO - Running script sql-scripts/build_up_db.sql ...
[2021-09-02 12:50:24,959] {__init__.py:121} INFO - Done.
[2021-09-02 12:50:24,992] {__init__.py:129} INFO - osmTGmod-database successfully built up!
[2021-09-02 12:50:24,992] {__init__.py:131} INFO - Importing OSM-data to database.
[2021-09-02 12:50:24,992] {__init__.py:133} INFO - Using pdf file: /home/student/git/eGon-data/src/egon/data/datasets/osm/schleswig-holstein-210101.osm.pbf
[2021-09-02 12:50:24,993] {__init__.py:134} INFO - Assuming osmosis is avaliable at
        osmosis/bin/osmosis
[2021-09-02 12:50:25,281] {taskinstance.py:1150} ERROR - 
| Command 'JAVACMD_OPTIONS='-Djava.io.tmpdir=osmTGmod/osmosis_temp'
| osmTGmod/osmosis/bin/osmosis --read-pbf /home/student/git/eGon-
| data/src/egon/data/datasets/osm/schleswig-holstein-210101.osm.pbf
| --write-pgsql                 database=egon-data host=127.0.0.1:59734
| user=egon password=data' returned non-zero exit status 1.
| Output:
| Errors:
|   Error: Could not find or load main class
|   test.osmTGmod.osmosis.lib.default.plexus-classworlds-*.jar
|   Caused by: java.lang.ClassNotFoundException:
|   test.osmTGmod.osmosis.lib.default.plexus-classworlds-*.jar
Traceback (most recent call last):
  File "/home/student/venv/egon-data_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/student/git/eGon-data/src/egon/data/datasets/__init__.py", line 192, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/student/venv/egon-data_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/student/venv/egon-data_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/student/git/eGon-data/src/egon/data/datasets/osmtgmod/__init__.py", line 144, in import_osm_data
    subproc.run(
  File "/home/student/git/eGon-data/src/egon/data/subprocess.py", line 60, in run
    raise CalledProcessError(
egon.data.subprocess.CalledProcessError: 
| Command 'JAVACMD_OPTIONS='-Djava.io.tmpdir=osmTGmod/osmosis_temp'
| osmTGmod/osmosis/bin/osmosis --read-pbf /home/student/git/eGon-
| data/src/egon/data/datasets/osm/schleswig-holstein-210101.osm.pbf
| --write-pgsql                 database=egon-data host=127.0.0.1:59734
| user=egon password=data' returned non-zero exit status 1.
| Output:
| Errors:
|   Error: Could not find or load main class
|   test.osmTGmod.osmosis.lib.default.plexus-classworlds-*.jar
|   Caused by: java.lang.ClassNotFoundException:
|   test.osmTGmod.osmosis.lib.default.plexus-classworlds-*.jar
[2021-09-02 12:50:25,286] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=osmtgmod.import-osm-data, execution_date=20210902T103712, start_date=20210902T105001, end_date=20210902T105025
[2021-09-02 12:50:26,507] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by IlkaCu** [comment]
@gnn: Do you have any ideas what might be the problem here?

**Comment by gnn** [comment]
My first guess would be that `osmosis` isn't available. Could you give me the commit hash from which you're running?

**Comment by CarlosEpia** [comment]
I'm running this branch right now: https://github.com/openego/eGon-data/tree/distribute-wind-offshore-capacities. But I also tried using the dev branch and got the same error. Regarding `Osmosis`, which package includes it during the installation process?
