### ISSUE TITLE
Rerunning full workflow fails in demandregio.install_disaggregator.clone-and-install

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#466]
The task fails when it is repeated and the directory `demandregio-disaggregator/...` is not empty (probably from prior runs).

```
Traceback (most recent call last):
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/demandregio/install_disaggregator.py", line 27, in clone_and_install
    shutil.rmtree(repo_path)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/shutil.py", line 659, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/shutil.py", line 657, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'data_out'
```

**Comment by fwitte** [comment]
Seemed to be an Oldenburg issue, was resolved by deleting all files in the working directory before restarting a new DAG run.
