### ISSUE TITLE
Import of egon missing in heat_demand_timeseries HTS.py module

### ISSUE THREAD

**Issue by fwitte** [openego/eGon-data#479]
https://github.com/openego/eGon-data/blob/73865d0715b1152eebb6c1c236af9a9feeb367e1/src/egon/data/datasets/heat_demand_timeseries/HTS.py#L774

is called in the process, however missing `import egon`. We could also add something like `from egon.data.config import settings` and directly call `settings()`. `from egon.data import config` like in other modules is not possible as config is also imported from the `disaggregator` package.

``` bash
Traceback (most recent call last):
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/witt_fa/anaconda3/envs/egon_env/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 1614, in demand_profile_generator
    ) = residential_demand_scale(aggregation_level)
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 1095, in residential_demand_scale
    annual_demand, heat_profile_dist, heat_profile_idp = profile_generator(
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 985, in profile_generator
    annual_demand, idp_df, selected_profiles = profile_selector()
  File "/home/witt_fa/eGon/eGon-data/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 774, in profile_selector
    seed=egon.data.config.settings()["egon-data"]["--random-seed"]
NameError: name 'egon' is not defined
```

**Comment by fwitte** [comment]
Hi @aadit879,
can we close this and #480? I just saw, that the task was successful on the CI run.

**Comment by aadit879** [comment]
> Hi @aadit879, can we close this and #480? I just saw, that the task was successful on the CI run.

Yes this is solved. I will close it.
