### ISSUE TITLE
chp.extension_HH and chp.extension_NW failed in first attempt on CI branch

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#517]
During the latest run of our CI branch the tasks `chp.extension_HH` and `chp.extension_NW` failed on the first attempt. After clearing the tasks they succeeded. It might be related to missing dependencies.

Log `chp.extension_HH`: 

```
[2021-11-15 12:04:06,994] {logging_mixin.py:120} WARNING - /home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
[2021-11-15 12:52:58,290] {taskinstance.py:1150} ERROR - 'a' cannot be empty unless no samples are taken
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/__init__.py", line 359, in extension_HH
    extension_per_federal_state("Hamburg", EgonChp)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 582, in extension_per_federal_state
    not_distributed_capacity_dh = extension_district_heating(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 401, in extension_district_heating
    not_distributed_capacity = extension_to_areas(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 211, in extension_to_areas
    id_chp = np.random.choice(range(len(possible_chp)))
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Log `chp.extension_NW`: 

```
[2021-11-15 14:13:22,994] {logging_mixin.py:120} WARNING - /home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
[2021-11-15 14:31:51,991] {taskinstance.py:1150} ERROR - 'GeoDataFrame' object has no attribute 'bus_id_right'
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/__init__.py", line 375, in extension_NW
    extension_per_federal_state("NordrheinWestfalen", EgonChp)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 582, in extension_per_federal_state
    not_distributed_capacity_dh = extension_district_heating(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 401, in extension_district_heating
    not_distributed_capacity = extension_to_areas(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/chp/small_chp.py", line 217, in extension_to_areas
    selected_areas.loc[:, "bus_id"] = assign_bus_id(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/power_plants/__init__.py", line 520, in assign_bus_id
    power_plants.loc[power_plants_ehv, "bus_id"] = gpd.sjoin(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'bus_id_right'
```

**Comment by ClaraBuettner** [comment]
I fixed this problem with 06e6767200f5c7d82025fda8025e30c9826cbca7 and e467643 in PR #501. 
I tested it manually on the server and merged the new changes into the CI-branch.
