### ISSUE TITLE
Task chp.extension-SH is failing in Oldenburg

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#521]
In the Oldenburg server, the task chp.extension-SH is failing with the following error message:
```
*** Reading local file: /opt/egon_data_workflow/wd_test_mode/airflow/logs/egon-data-processing-pipeline/chp.extension-SH/2021-11-16T14:50:29.482768+00:00/1.log
[2021-11-17 14:06:34,529] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-11-16T14:50:29.482768+00:00 [queued]>
[2021-11-17 14:06:34,757] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-11-16T14:50:29.482768+00:00 [queued]>
[2021-11-17 14:06:34,758] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 14:06:34,758] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-11-17 14:06:34,758] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 14:06:34,787] {taskinstance.py:901} INFO - Executing <Task(Chp (versioned)): chp.extension-SH> on 2021-11-16T14:50:29.482768+00:00
[2021-11-17 14:06:34,799] {standard_task_runner.py:54} INFO - Started process 28142 to run task
[2021-11-17 14:06:34,881] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'chp.extension-SH', '2021-11-16T14:50:29.482768+00:00', '--job_id', '4644', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpjnbzuisr']
[2021-11-17 14:06:34,882] {standard_task_runner.py:78} INFO - Job 4644: Subtask chp.extension-SH
[2021-11-17 14:06:35,145] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-11-16T14:50:29.482768+00:00 [running]> on host torch.esy.ve.dlr
[2021-11-17 14:06:38,347] {logging_mixin.py:120} INFO - Target capacity in SchleswigHolstein: 300.0
[2021-11-17 14:06:38,347] {logging_mixin.py:120} INFO - Existing capacity in SchleswigHolstein: 151.8315
[2021-11-17 14:06:38,350] {logging_mixin.py:120} INFO - Distributing 148.1685 MW_el in SchleswigHolstein
[2021-11-17 14:06:38,350] {logging_mixin.py:120} INFO - Distributing 108.83255742286678 MW_el to district heating
[2021-11-17 14:06:55,533] {utils.py:145} INFO - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-11-17 14:06:55,533] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2021-11-17 14:07:05,522] {logging_mixin.py:120} WARNING - /home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
[2021-11-17 14:19:46,340] {logging_mixin.py:120} INFO - Distributing 39.3359425771332 MW_el to industry
[2021-11-17 14:22:32,283] {taskinstance.py:1150} ERROR - Some power plants are
    not attached to a bus:           demand  osm_id  ... voltage_level bus_id
264  8382.894241  398305  ...           6.0    NaN

[1 rows x 7 columns]
Traceback (most recent call last):
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/__init__.py", line 298, in extension_SH
    extension_per_federal_state("SchleswigHolstein", EgonChp)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 588, in extension_per_federal_state
    not_distributed_capacity_industry = extension_industrial(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 491, in extension_industrial
    not_distributed_capacity = extension_to_areas(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 216, in extension_to_areas
    selected_areas.loc[:, "bus_id"] = assign_bus_id(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/power_plants/__init__.py", line 533, in assign_bus_id
    assert power_plants.bus_id.notnull().all(), f"""Some power plants are
AssertionError: Some power plants are
    not attached to a bus:           demand  osm_id  ... voltage_level bus_id
264  8382.894241  398305  ...           6.0    NaN

[1 rows x 7 columns]
[2021-11-17 14:22:32,513] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=chp.extension-SH, execution_date=20211116T145029, start_date=20211117T130634, end_date=20211117T132232
[2021-11-17 14:22:33,472] {local_task_job.py:102} INFO - Task exited with return code 1
```

We guess that this problem is related to the issue https://github.com/openego/eGon-data/issues/488, because this one is also only affecting the Oldenburg server.

**Comment by AmeliaNadal** [comment]
Without real explanation, this task is not failing anymore in Oldenburg.
