### ISSUE TITLE
Conflicting package versions in egon-data installation 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#556]
I installed egon-data in a new environment but some package versions were conflicting each other. To start airflow I had to install some package versions manually:

- jsonschema~=3.0
- requests <2.24.0
- attrs<21.0
- importlib-resources~=1.4
- importlib-metadata ~=2.0
- click<8
- itsdangerous<2.0
- PyJWT<2.0
- WTForms==2.3.3

I use python 3.8.10 and pip 20.1.1

**Comment by nesnoj** [comment]
Is this the same problem as in #641?

**Comment by gnn** [comment]
> Is this the same problem as in #641?

Not exactly the same problem, but the `WTForms==2.3.3` line would take care of issue #641, so they are at least partially related.

**Comment by gnn** [comment]
PR #692 should fix this. Would you mind testing whether this is correct?

**Comment by ClaraBuettner** [comment]
> PR #692 should fix this. Would you mind testing whether this is correct?

I can install egon-data without any problems, but when I try to start it with `egon-data serve` I run into this error: 
```
Traceback (most recent call last):
  File "/home/clara/692-egon-data/test-venv/bin/egon-data", line 33, in <module>
    sys.exit(load_entry_point('egon.data', 'console_scripts', 'egon-data')())
  File "/home/clara/692-egon-data/eGon-data/src/egon/data/cli.py", line 443, in main
    egon_data.main(sys.argv[1:])
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/clara/692-egon-data/eGon-data/src/egon/data/cli.py", line 339, in egon_data
    from airflow.configuration import conf as airflow_cfg
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/airflow/__init__.py", line 43, in <module>
    from flask_admin import BaseView
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/flask_admin/__init__.py", line 6, in <module>
    from .base import expose, expose_plugview, Admin, BaseView, AdminIndexView  # noqa: F401
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/flask_admin/base.py", line 6, in <module>
    from flask import Blueprint, current_app, render_template, abort, g, url_for
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/clara/692-egon-data/test-venv/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

I created a new python3.8.10 environment; these attached packages were installed by running `pip install -e eGon-data/`:
[requirements.txt](https://github.com/openego/eGon-data/files/8253061/requirements.txt)

**Comment by gnn** [comment]
That's funny. Looking at the attached file reveals a broken installation due to conflicting package versions: `Flask == 1.1.4` is installed alongside `itsdangerous == 2.1.1`, but `Flask == 1.1.4` has the constraint [`itsdangerous < 2.0`][0]. So `pip` should either refuse to install this package configuration or warn you that you have conflicting package versions.
Would you mind creating a fresh Python 3.8.10 environment and posting the output of `pip freeze` directly after creating the environment and then again after doing `pip install -U pip`? Also, what's the output of doing `pip check` inside the environment from the post above?

[0]: https://github.com/pallets/flask/blob/1ca199f9b38b70a4e97cb47a4252ffd7fccc008c/setup.py#L58

**Comment by ClaraBuettner** [comment]
I created a new environment and installed egon-data. The packages listed in [packages_pip20_1_1.txt](https://github.com/openego/eGon-data/files/8813937/packages_pip20_1_1.txt) were installed. The output of `pip check` was: 
```
geovoronoi 0.3.0 has requirement shapely<1.8,>=1.7.0, but you have shapely 1.8.2.
flask 1.1.4 has requirement click<8.0,>=5.1, but you have click 8.1.3.
flask 1.1.4 has requirement Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2.
flask-jwt-extended 3.25.1 has requirement PyJWT<2.0,>=1.6.4, but you
[packages_pip20_1_1.txt](https://github.com/openego/eGon-data/files/8813929/packages_pip20_1_1.txt)
[packages_pip20_1_1.txt](https://github.com/openego/eGon-data/files/8813934/packages_pip20_1_1.txt)
 have pyjwt 2.4.0.
flask-appbuilder 2.3.4 has requirement click<8,>=6.7, but you have click 8.1.3.
flask-appbuilder 2.3.4 has requirement jsonschema<4,>=3.0.1, but you have jsonschema 4.5.1.
flask-appbuilder 2.3.4 has requirement marshmallow<3.0.0,>=2.18.0, but you have marshmallow 3.16.0.
apache-airflow 1.10.15 has requirement attrs<21.0,>=20.0, but you have attrs 21.4.0.
apache-airflow 1.10.15 has requirement importlib-resources~=1.4, but you have importlib-resources 5.7.1.
apache-airflow 1.10.15 has requirement jinja2<2.12.0,>=2.10.1, but you have jinja2 3.1.2.
apache-airflow 1.10.15 has requirement jsonschema~=3.0, but you have jsonschema 4.5.1.
apache-airflow 1.10.15 has requirement requests<2.24.0,>=2.20.0; python_version >= "3.0", but you have requests 2.27.1.
```
`egon-data serve` results in this error: 
```
  File "/home/clara/new-test-egon-data/venv/lib/python3.8/site-packages/airflow/__init__.py", line 43, in <module>
    from flask_admin import BaseView
  File "/home/clara/new-test-egon-data/venv/lib/python3.8/site-packages/flask_admin/__init__.py", line 6, in <module>
    from .base import expose, expose_plugview, Admin, BaseView, AdminIndexView  # noqa: F401
  File "/home/clara/new-test-egon-data/venv/lib/python3.8/site-packages/flask_admin/base.py", line 6, in <module>
    from flask import Blueprint, current_app, render_template, abort, g, url_for
  File "/home/clara/new-test-egon-data/venv/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/clara/new-test-egon-data/venv/lib/python3.8/site-packages/jinja2/__init__.py)
```


I updated pip as you described above and reinstalled eGon-data. Now, the packages listed in [packages_pip22_1_2.txt](https://github.com/openego/eGon-data/files/8813995/packages_pip22_1_2.txt) are installed. 
`pip check` returns no conflicts anymore. 

So, updating pip solved all these dependency issues, thank you! Can we document this solution somewhere?

**Comment by nailend** [comment]
Updating `pip` with `pip install -U pip` and reinstalling `egon-data` also solved the problem for me
