### ISSUE TITLE
Airflow webserver raises `TypeError: Object of type Undefined is not JSON serializable`

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#665]
After a fresh install and using `continuous-integration/run-everything-over-the-weekend-v2`, `egon-data serve` starts up properly, but accessing the webinterface gives

```
                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: XXXXX
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/views.py", line 431, in index
    return self.render('airflow/dags.html')
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/views.py", line 421, in render
    return super(AirflowViewMixin, self).render(template, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/templates/airflow/dags.html", line 20, in top-level template code
    {% extends "airflow/master.html" %}
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/templates/airflow/master.html", line 20, in top-level template code
    {% extends "admin/master.html" %}
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/templates/admin/master.html", line 20, in top-level template code
    {% extends 'admin/base.html' %}
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 95, in top-level template code
    {% block tail %}
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/www/templates/airflow/dags.html", line 220, in block "tail"
    const STATE_COLOR = {{ state_color|tojson }};
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 376, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 290, in htmlsafe_dumps
    dumps(obj, **kwargs)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Undefined is not JSON serializable
```
Packages: [pip_freeze_eGon-data-sh2.txt](https://github.com/openego/eGon-data/files/8079377/pip_freeze_eGon-data-sh2.txt)

Any ideas, @gnn ?

**Comment by nesnoj** [comment]
This seems to be resolved although only datasets seem to have changed. o_O
Closing...

**Comment by gnn** [comment]
Weird. For what it's worth, I checked the linked pip freeze output against what's used for the weekend run and the only package which is older in the weekend run compared to the linked versions is "hijri-converter==2.2.0". I would've asked you to downgrade and try again, but since the problem is not reproducible any more, this note serves only as a reminder in case the issue crops up again.
