### ISSUE TITLE
Dependency error in `heat_etrago.buses`

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#800]
When running the current dev in testmode (same result for two separate runs on two different machines) the task `heat_etrago.buses` produces the error below. Re-running the task at a later point in time works out. Seems to be caused by a missing dependency.

```
[2022-06-08 02:06:17,765] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_timeseries_individual_heating" does not exist
LINE 7:                 demand.egon_etrago_timeseries_individual_hea...
                        ^

[SQL: 
            SELECT ST_Centroid(geom) AS geom
            FROM grid.
            egon_mv_grid_district
            WHERE bus_id IN (
                SELECT bus_id FROM 
                demand.egon_etrago_timeseries_individual_heating
                WHERE scenario = 'eGon2035')
            ]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "demand.egon_etrago_timeseries_individual_heating" does not exist
LINE 7:                 demand.egon_etrago_timeseries_individual_hea...
                        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/heat_etrago/__init__.py", line 575, in buses
    insert_buses("rural_heat", scenario="eGon2035")
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/heat_etrago/__init__.py", line 67, in insert_buses
    mv_grids = db.select_geodataframe(
  File "/storage/eGon-data-sh/code/src/egon/data/db.py", line 210, in select_geodataframe
    gdf = gpd.read_postgis(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/geopandas/io/sql.py", line 154, in _read_postgis
    df = pd.read_sql(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 521, in read_sql
    return pandas_sql.read_query(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1308, in read_query
    result = self.execute(*args)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1176, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_timeseries_individual_heating" does not exist
LINE 7:                 demand.egon_etrago_timeseries_individual_hea...
                        ^

[SQL: 
            SELECT ST_Centroid(geom) AS geom
            FROM grid.
            egon_mv_grid_district
            WHERE bus_id IN (
                SELECT bus_id FROM 
                demand.egon_etrago_timeseries_individual_heating
                WHERE scenario = 'eGon2035')
            ]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by ClaraBuettner** [comment]
Is this the same error reported in #771? I will fix this.

**Comment by nesnoj** [comment]
Yes, same same.
