### ISSUE TITLE
Duplicate key values in get_annual_household_el_demand_cells

### ISSUE THREAD

**Issue by khelfen** [openego/eGon-data#812]
Running the current `dev` for SH gives me the following duplicate key value error. Any idea why this could happen?

```
[2022-06-13 18:02:07,303] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.electricity_demand.get-annual-household-el-demand-cells 2022-06-13T13:04:17.556191+00:00 [queued]>
[2022-06-13 18:02:07,333] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.electricity_demand.get-annual-household-el-demand-cells 2022-06-13T13:04:17.556191+00:00 [queued]>
[2022-06-13 18:02:07,333] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 18:02:07,333] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2022-06-13 18:02:07,333] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 18:02:07,344] {taskinstance.py:901} INFO - Executing <Task(HouseholdElectricityDemand (versioned)): electricity_demand.get-annual-household-el-demand-cells> on 2022-06-13T13:04:17.556191+00:00
[2022-06-13 18:02:07,349] {standard_task_runner.py:54} INFO - Started process 286521 to run task
[2022-06-13 18:02:07,506] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'electricity_demand.get-annual-household-el-demand-cells', '2022-06-13T13:04:17.556191+00:00', '--job_id', '146', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp5c_2qp18']
[2022-06-13 18:02:07,506] {standard_task_runner.py:78} INFO - Job 146: Subtask electricity_demand.get-annual-household-el-demand-cells
[2022-06-13 18:02:07,538] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.electricity_demand.get-annual-household-el-demand-cells 2022-06-13T13:04:17.556191+00:00 [running]> on host RLI-NB-91
[2022-06-13 19:18:23,408] {taskinstance.py:1150} ERROR - (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "egon_demandregio_zensus_electricity_pkey"
DETAIL:  Key (zensus_population_id, scenario, sector)=(173, eGon2035, residential) already exists.

[SQL: INSERT INTO demand.egon_demandregio_zensus_electricity (zensus_population_id, sector, scenario, demand) VALUES (%(zensus_population_id)s, %(sector)s, %(scenario)s, %(demand)s)]
[parameters: ({'zensus_population_id': 173, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 9.885219674959647}, {'zensus_population_id': 210, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 9.768333133825637}, {'zensus_population_id': 240, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 10.252322565922409}, {'zensus_population_id': 242, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 40.567012883539036}, {'zensus_population_id': 243, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 183.06031685630154}, {'zensus_population_id': 244, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 97.68276249376666}, {'zensus_population_id': 245, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 108.18166372298843}, {'zensus_population_id': 246, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 112.37782434167902}  ... displaying 10 of 287042 total bound parameter sets ...  {'zensus_population_id': 1578482, 'sector': 'residential', 'scenario': 'eGon100RE', 'demand': 12.408329451417082}, {'zensus_population_id': 1579340, 'sector': 'residential', 'scenario': 'eGon100RE', 'demand': 7.31255384453361})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "egon_demandregio_zensus_electricity_pkey"
DETAIL:  Key (zensus_population_id, scenario, sector)=(173, eGon2035, residential) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/kilian/Documents/PythonProjects/eGon/eGon-data/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kilian/Documents/PythonProjects/eGon/eGon-data/src/egon/data/datasets/electricity_demand/__init__.py", line 156, in get_annual_household_el_demand_cells
    df_annual_demand.to_sql(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/core/generic.py", line 2872, in to_sql
    sql.to_sql(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 1761, in to_sql
    sql_engine.insert_records(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 1350, in insert_records
    raise err
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/pandas/io/sql.py", line 882, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/home/kilian/anaconda3/envs/d_py38_egon_data_conda/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 912, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "egon_demandregio_zensus_electricity_pkey"
DETAIL:  Key (zensus_population_id, scenario, sector)=(173, eGon2035, residential) already exists.

[SQL: INSERT INTO demand.egon_demandregio_zensus_electricity (zensus_population_id, sector, scenario, demand) VALUES (%(zensus_population_id)s, %(sector)s, %(scenario)s, %(demand)s)]
[parameters: ({'zensus_population_id': 173, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 9.885219674959647}, {'zensus_population_id': 210, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 9.768333133825637}, {'zensus_population_id': 240, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 10.252322565922409}, {'zensus_population_id': 242, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 40.567012883539036}, {'zensus_population_id': 243, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 183.06031685630154}, {'zensus_population_id': 244, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 97.68276249376666}, {'zensus_population_id': 245, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 108.18166372298843}, {'zensus_population_id': 246, 'sector': 'residential', 'scenario': 'eGon2035', 'demand': 112.37782434167902}  ... displaying 10 of 287042 total bound parameter sets ...  {'zensus_population_id': 1578482, 'sector': 'residential', 'scenario': 'eGon100RE', 'demand': 12.408329451417082}, {'zensus_population_id': 1579340, 'sector': 'residential', 'scenario': 'eGon100RE', 'demand': 7.31255384453361})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2022-06-13 19:18:23,414] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=electricity_demand.get-annual-household-el-demand-cells, execution_date=20220613T130417, start_date=20220613T160207, end_date=20220613T171823
[2022-06-13 19:18:26,913] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ClaraBuettner** [comment]
I don't have any ideas why this could happen by now. Besides, I didn't implement the current version of this function, I think it was done by @nailend

**Comment by nailend** [comment]
I had a look at the code. From my understanding, it should only happen if the function "get_annual_household_el_demand_cells" runs twice as the result is appended to the table if existing. Will have to check it next week.
