### ISSUE TITLE
Secret_key to run the flask app

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#83]
With the new version of eGon-data (download yesterday 07.01.21 evening but with Apache-airflow version 1.10.14), I had the following error message (complete output below):
ERROR: The `secret_key` setting under the webserver config has an insecure value - Airflow has failed safe and refuses to start. Please change this value to a new, per-environment, randomly generated string, for example using this command `openssl rand -hex 30`
I could locally solve the problem thanks @gplssm by:
- getting a secret key by executing the command `openssl rand -hex 30`.
- in the airflow.cfg (eGon-data/src/egon/data/airflow/airflow.cfg), line 335 replacing `temporary_key` by the obtained secret key.
But I guess this should be fixed.

Complete output:
Traceback (most recent call last):
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/subprocess.py", line 1122, in communicate
    self.wait()
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/subprocess.py", line 1185, in wait
    return self._wait(timeout=timeout)
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/subprocess.py", line 1915, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/nada_am/anaconda3/envs/egondata_dlrtests_env/lib/python3.9/subprocess.py", line 1873, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
^C
(egondata_dlrtests_env) nada_am@torch:~/AN_eGon/eGon_code/eGon-data/git_eGon-data_dlr_tests/eGon-data$ egon-data serve
The 'initdb' command is deprecated and removed in Airflow 2.0, please use 'db init' instead
DB: sqlite:////home/nada_am/AN_eGon/eGon_code/eGon-data/git_eGon-data_dlr_tests/eGon-data/src/egon/data/airflow/airflow.db
[2021-01-08 12:34:25,351] {db.py:378} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [airflow.models.crypto] empty cryptography key - values will not be stored encrypted.
print_test_0
print_test_1
Done.
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
ERROR: The `secret_key` setting under the webserver config has an insecure value - Airflow has failed safe and refuses to start. Please change this value to a new, per-environment, randomly generated string, for example using this command `openssl rand -hex 30`

**Comment by gnn** [comment]
Could you try setting `secret_key = {SECRET_KEY}` in "src/egon/data/airflow/airflow.cfg"? That should let `egon-data serve` run without this error again.

**Comment by AmeliaNadal** [comment]
I have tried setting secret_key = {SECRET_KEY} in "src/egon/data/airflow/airflow.cfg" and it lets egon-data serve run without the error. Should I close the issue?
