### ISSUE TITLE
Missing dependency in `heat_demand_timeseries.HTS.demand-profile-generator`

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#834]
era5 is missing in dependencies.
This was supposed to be solved in #725 but apparently missed.

Full log:
```
[2022-07-07 11:27:47,214] {standard_task_runner.py:78} INFO - Job 97: Subtask heat_demand_timeseries.HTS.demand-profile-generator
[2022-07-07 11:27:47,338] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.heat_demand_timeseries.HTS.demand-profile-generator 2022-07-07T08:34:30.910662+00:00 [running]> on host ws-02lin.rl-institut.local
[2022-07-07 11:31:18,478] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py:644: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  boundaries_buffer.geometry = boundaries_buffer.geometry.buffer(buffer)
[2022-07-07 11:31:18,500] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py:1011: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  annual_demand, idp_df, selected_profiles = profile_selector()
[2022-07-07 11:31:18,533] {logging_mixin.py:120} INFO - Maximal buffer to match zensus points to climate zones: 100m
[2022-07-07 11:31:20,926] {cutout.py:186} INFO - Building new cutout /storage/eGon-data-sh2/working-dir/cutouts/germany-2011-era5.nc
[2022-07-07 11:31:21,019] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
 
        SELECT geom FROM supply.egon_era5_weather_cells
[2022-07-07 11:31:21,025] {convert.py:111} INFO - Convert and aggregate 'temperature'.
[2022-07-07 11:31:21,026] {taskinstance.py:1150} ERROR - 'temperature'
Traceback (most recent call last):
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1398, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'temperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 1796, in demand_profile_generator
    ) = residential_demand_scale(aggregation_level)
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 1156, in residential_demand_scale
    annual_demand, heat_profile_dist, heat_profile_idp = profile_generator(
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 1011, in profile_generator
    annual_demand, idp_df, selected_profiles = profile_selector()
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 747, in profile_selector
    all_temperature_interval = temp_interval()
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 202, in temp_interval
    temp_profile = temperature_profile_extract()
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/heat_demand_timeseries/HTS.py", line 183, in temperature_profile_extract
    temperature_profile = cutout.temperature(
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/atlite/convert.py", line 183, in temperature
    return cutout.convert_and_aggregate(convert_func=convert_temperature, **params)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/atlite/convert.py", line 112, in convert_and_aggregate
    da = convert_func(cutout.data, **convert_kwds)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/atlite/convert.py", line 179, in convert_temperature
    return ds["temperature"] - 273.15
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1502, in __getitem__
    return self._construct_dataarray(key)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 1400, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 173, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'temperature'
[2022-07-07 11:31:21,046] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=heat_demand_timeseries.HTS.demand-profile-generator, execution_date=20220707T083430, start_date=20220707T092747, end_date=20220707T093121
[2022-07-07 11:31:23,116] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ClaraBuettner** [comment]
This bug was introduced by #402 which was only merged into CI and not into dev yet. I fixed the problem in d2002d90510af16a3e6ce4d95562e08306eadeae.
