### ISSUE TITLE
dependency error afer fresh egon-data install

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#842]
I got the following error after doing a fresh install of the dev on a linux-server. Couldn't start airflow as well

```ERROR: flask 1.1.4 has requirement click<8.0,>=5.1, but you'll have click 8.1.3 which is incompatible.
ERROR: flask 1.1.4 has requirement Jinja2<3.0,>=2.10.1, but you'll have jinja2 3.1.2 which is incompatible.
ERROR: flask-jwt-extended 3.25.1 has requirement PyJWT<2.0,>=1.6.4, but you'll have pyjwt 2.4.0 which is incompatible.
ERROR: flask-appbuilder 2.3.4 has requirement click<8,>=6.7, but you'll have click 8.1.3 which is incompatible.
ERROR: flask-appbuilder 2.3.4 has requirement jsonschema<4,>=3.0.1, but you'll have jsonschema 4.7.2 which is incompatible.
ERROR: flask-appbuilder 2.3.4 has requirement marshmallow<3.0.0,>=2.18.0, but you'll have marshmallow 3.17.0 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement attrs<21.0,>=20.0, but you'll have attrs 21.4.0 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement importlib-resources~=1.4, but you'll have importlib-resources 5.8.0 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement jinja2<2.12.0,>=2.10.1, but you'll have jinja2 3.1.2 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement jsonschema~=3.0, but you'll have jsonschema 4.7.2 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement requests<2.24.0,>=2.20.0; python_version >= "3.0", but you'll have requests 2.28.1 which is incompatible.
ERROR: geovoronoi 0.3.0 has requirement scipy<1.7,>=1.5.0, but you'll have scipy 1.8.1 which is incompatible.
ERROR: geovoronoi 0.3.0 has requirement shapely<1.8,>=1.7.0, but you'll have shapely 1.8.2 which is incompatible.
```
After merging #811

```
ERROR: flask 1.1.4 has requirement click<8.0,>=5.1, but you'll have click 8.1.3 which is incompatible.
ERROR: flask 1.1.4 has requirement itsdangerous<2.0,>=0.24, but you'll have itsdangerous 2.1.2 which is incompatible.
ERROR: flask-jwt-extended 3.25.1 has requirement PyJWT<2.0,>=1.6.4, but you'll have pyjwt 2.4.0 which is incompatible.
ERROR: flask-appbuilder 2.3.4 has requirement click<8,>=6.7, but you'll have click 8.1.3 which is incompatible.
ERROR: apache-airflow 1.10.15 has requirement importlib-resources~=1.4, but you'll have importlib-resources 5.8.0 which is incompatible.
ERROR: snakemake 7.9.0 has requirement jinja2<4.0,>=3.0, but you'll have jinja2 2.11.3 which is incompatible.
ERROR: geovoronoi 0.3.0 has requirement scipy<1.7,>=1.5.0, but you'll have scipy 1.8.1 which is incompatible.
ERROR: geovoronoi 0.3.0 has requirement shapely<1.8,>=1.7.0, but you'll have shapely 1.8.2 which is incompatible.
ERROR: black 21.12b0 has requirement tomli<2.0.0,>=0.2.6, but you'll have tomli 2.0.1 which is incompatible.
```

```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/airflow/configuration.py:762: DeprecationWarning: You have two airflow.cfg files: /home/local/RL-INSTITUT/julian.endres/airflow/airflow.cfg and /storage/eGon-data-sh-cts/working-dir/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /storage/eGon-data-sh-cts/working-dir/airflow/airflow.cfg, and you should remove the other file
  warnings.warn(
Traceback (most recent call last):
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/bin/egon-data", line 33, in <module>
    sys.exit(load_entry_point('egon.data', 'console_scripts', 'egon-data')())
  File "/storage/eGon-data-sh-cts/eGon-data/src/egon/data/cli.py", line 443, in main
    egon_data.main(sys.argv[1:])
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/storage/eGon-data-sh-cts/eGon-data/src/egon/data/cli.py", line 339, in egon_data
    from airflow.configuration import conf as airflow_cfg
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/airflow/__init__.py", line 43, in <module>
    from flask_admin import BaseView
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/flask_admin/__init__.py", line 6, in <module>
    from .base import expose, expose_plugview, Admin, BaseView, AdminIndexView  # noqa: F401
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/flask_admin/base.py", line 6, in <module>
    from flask import Blueprint, current_app, render_template, abort, g, url_for
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/storage/eGon-data-sh-cts/d_py38_egon-data-cts/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

**Comment by nailend** [comment]
solved after upgrading pip and using bash instead of zshell...
