### ISSUE TITLE
Conflicting ids in osmtgmod_substation

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#856]
When the substation dataset was skipped because of versioning but osmtgmod was executed, the task `osmtgmod.osmtgmod_substation` fails because of conflicting ids: 

```
[2022-08-01 09:01:46,087] {taskinstance.py:1150} ERROR - duplicate key value violates unique constraint "egon_hvmv_substation_pkey"
DETAIL:  Key (bus_id)=(35352) already exists.
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "egon_hvmv_substation_pkey"
DETAIL:  Key (bus_id)=(35352) already exists.

[2022-08-01 09:01:46,090] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=osmtgmod_substation, execution_date=20220729T154153, start_date=20220801T070145, end_date=20220801T070146
[2022-08-01 09:01:50,649] {local_task_job.py:102} INFO - Task exited with return code 1
```
It might be related to #769 
We could solve it by using different tables for the results from the substation and the osmtgmod-substation dataset. 

This problem occured during the latest CI-run. I will add a `.dev `to the version number of the substation-dataset temporary.

**Comment by ClaraBuettner** [comment]
I would suggest to rename the output tables from the substation dataset to `grid.egon_ehv_transfer_buses` and `grid.egon_hvmv_transfer_buses`. The substation tables (e.g. `grid.egon_ehv_substation`) would be created in `osmtgmod.osmtgmod_substation` based on the transfer buses tables. 
This would mean that we have two additional tables with somehow redundant data. But since these are only smaller tables, I think it is worth the better understanding of the table structures.
