### ISSUE TITLE
district_heating_areas.demarcation is failing at RLI

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#865]
Hello like-minded, I am running into an error in `district_heating_areas.demarcation`. My branch is up-to-date with dev. 

```
[2022-08-03 14:43:29,118] {taskinstance.py:901} INFO - Executing <Task(District-heating-areas (versioned)): district_heating_areas.demarcation> on 2022-08-03T12:18:10.890399+00:00
[2022-08-03 14:43:29,127] {standard_task_runner.py:54} INFO - Started process 3611384 to run task
[2022-08-03 14:43:29,176] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'district_heating_areas.demarcation', '2022-08-03T12:18:10.890399+00:00', '--job_id', '58', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp_5rf3o1z']
[2022-08-03 14:43:29,176] {standard_task_runner.py:78} INFO - Job 58: Subtask district_heating_areas.demarcation
[2022-08-03 14:43:29,717] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.district_heating_areas.demarcation 2022-08-03T12:18:10.890399+00:00 [running]> on host ws-02lin.rl-institut.local
[2022-08-03 14:43:41,602] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py:1134: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  heat_density_per_scenario["eGon2035"] = district_heating_areas(
[2022-08-03 14:44:07,970] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py:1134: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  heat_density_per_scenario["eGon2035"] = district_heating_areas(
[2022-08-03 14:44:16,096] {logging_mixin.py:120} INFO - Minimum heat demand density for cells with new district heat
          supply in scenario eGon2035 is
          1056.696798644044
          MWh / (ha a).
[2022-08-03 14:44:16,096] {logging_mixin.py:120} INFO - Number of cells with new district heat supply in scenario
          eGon2035 is 365.
[2022-08-03 14:44:17,967] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py:1134: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  heat_density_per_scenario["eGon2035"] = district_heating_areas(
[2022-08-03 14:44:18,653] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py:1134: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  heat_density_per_scenario["eGon2035"] = district_heating_areas(
[2022-08-03 14:44:18,681] {taskinstance.py:1150} ERROR - issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py", line 1134, in demarcation
    heat_density_per_scenario["eGon2035"] = district_heating_areas(
  File "/storage/eGon-data-sh-je/eGon-data/src/egon/data/datasets/district_heating_areas/__init__.py", line 599, in district_heating_areas
    scenario_dh_area.groupby("area_id").size().sort_values()
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1828, in size
    if issubclass(self.obj._constructor, Series):
TypeError: issubclass() arg 1 must be a class
[2022-08-03 14:44:18,703] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=district_heating_areas.demarcation, execution_date=20220803T121810, start_date=20220803T124328, end_date=20220803T124418
[2022-08-03 14:44:19,059] {local_task_job.py:102} INFO - Task exited with return code 1
```

It's happening [here](https://github.com/openego/eGon-data/blob/d9a34a922980a50c7752e74629626a266e28b63f/src/egon/data/datasets/district_heating_areas/__init__.py#L599) but I dont really understand where its coming from. Anyone experiencing the same problem? The code apparently didnt change recently. Maybe a pandas thing?

**Comment by nailend** [comment]
As aadhoc fix I just commented this part as non off the actions have an effect anyways (inplace=False)

**Comment by ClaraBuettner** [comment]
This problem might be caused by the newest geopandas version (see #829). Could you try to install `geopandas==0.10.2` ?

**Comment by AmeliaNadal** [comment]
> This problem might be caused by the newest geopandas version (see #829). Could you try to install `geopandas==0.10.2` ?

This solved the problem for me :)

**Comment by nesnoj** [comment]
Has this solved the problem for you too @nailend ?

**Comment by nailend** [comment]
> As aadhoc fix I just commented this part as non off the actions have an effect anyways (inplace=False)



> Has this solved the problem for you too @nailend ?

I guess so but had it fixed, this way already
