### ISSUE TITLE
CI branch not starting airflow

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#876]
I can not start airflow using the current CI branch anymore. It looks like the problem is caused by merging #826: 

```
airflow.models.dagbag.DagBag: ERROR    Failed to import: /home/clara/test-egon-data/eGon-data/src/egon/data/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/clara/test-egon-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/airflow/dags/pipeline.py", line 27, in <module>
    from egon.data.datasets.electricity_demand_timeseries.cts_buildings import (
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/datasets/electricity_demand_timeseries/cts_buildings.py", line 7, in <module>
    import saio
ModuleNotFoundError: No module named 'saio'
```

**Comment by nesnoj** [comment]
Fixed in 30948e8 and merged into CI
