### ISSUE TITLE
Task `fix_ehv_subnetworks.run` fails in DE versioning run

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#892]
After retriggering for DE (last version, HEAD: 9cb41bcab935819f6d180b069ccbed4e80dc3188) `fix_ehv_subnetworks.run` fails (clean run was successful before):
```
[2022-08-26 10:18:16,293] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.fix_ehv_subnetworks.run 2022-08-25T06:21:13.860450+00:00 [running]> on host ws-02lin.rl-institut.local
[2022-08-26 10:18:22,868] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
 
        SELECT bus_id
        FROM grid.egon_etrago_bus
        WHERE x = 9.988215035677026
        AND y = 51.954230057487926
        AND v_nom = 380
        AND scn_name = 'eGon2035'
        AND carrier = 'AC'
[2022-08-26 10:18:22,869] {taskinstance.py:1150} ERROR - index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data3/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data3/code/src/egon/data/datasets/fix_ehv_subnetworks.py", line 370, in run
    fix_subnetworks("eGon2035")
  File "/storage/eGon-data3/code/src/egon/data/datasets/fix_ehv_subnetworks.py", line 293, in fix_subnetworks
    drop_line(
  File "/storage/eGon-data3/code/src/egon/data/datasets/fix_ehv_subnetworks.py", line 115, in drop_line
    bus0 = select_bus_id(x0, y0, v_nom, scn_name, carrier="AC")
  File "/storage/eGon-data3/code/src/egon/data/datasets/fix_ehv_subnetworks.py", line 25, in select_bus_id
    return db.select_dataframe(
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/pandas/core/series.py", line 939, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Can u reproduce this?

**Comment by nesnoj** [comment]
Works out now, thank you!
