### ISSUE TITLE
`heat_demand_timeseries.idp_pool.select` fails due to duplicate keys

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#893]
In DE run (clean and versioned):
```
[2022-08-26 12:09:28,616] {taskinstance.py:1150} ERROR - (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "heat_timeseries_selected_profiles_pkey"
DETAIL:  Key (zensus_population_id, building_id)=(15384500, 14848694) already exists.

[SQL: INSERT INTO demand.heat_timeseries_selected_profiles (zensus_population_id, building_id, selected_idp_profiles) VALUES (%(zensus_population_id_m0)s, %(building_id_m0)s, %(selected_idp_profiles_m0)s), (%(zensus_population_id_m1)s, %(building_id_m1)s [...]
[...]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/storage/eGon-data3/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "heat_timeseries_selected_profiles_pkey"
DETAIL:  Key (zensus_population_id, building_id)=(15384500, 14848694) already exists.
```

**Comment by ClaraBuettner** [comment]
I tried to find out why this happened, but there seems to be no duplicate data. I will try to remove the primary key setting for further investigations...

**Comment by ClaraBuettner** [comment]
I fixed this in https://github.com/openego/eGon-data/pull/870/commits/69b43c28ecbd12dfa0b174faee1b8319c1252cb3

**Comment by nesnoj** [comment]
thx!

**Comment by nesnoj** [comment]
thx!
