### ISSUE TITLE
Task `DSM_cts_ind.dsm-cts-ind-processing` fails on CI

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#911]
CI run (SH), task `DSM_cts_ind.dsm-cts-ind-processing`:
```
[2022-09-06 08:06:07,578] {logging_mixin.py:120} INFO - industry sites: pulp
[2022-09-06 08:06:07,578] {logging_mixin.py:120} INFO - 
[2022-09-06 08:06:07,743] {taskinstance.py:1150} ERROR - 'eGon2035'
Traceback (most recent call last):
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/DSM_cts_ind.py", line 1053, in dsm_cts_ind_processing
    dsm_cts_ind()
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/DSM_cts_ind.py", line 955, in dsm_cts_ind
    dsm_buses, dsm_links, dsm_stores = create_dsm_components(
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/DSM_cts_ind.py", line 452, in create_dsm_components
    dsm_id, dsm_id + rows_per_scenario["eGon2035"]
KeyError: 'eGon2035'
```

Full log: 
[egon-data-processing-pipeline_DSM_cts_ind.dsm-cts-ind-processing_2022-09-06T05_24_26.062835+00_00_2.log](https://github.com/openego/eGon-data/files/9494360/egon-data-processing-pipeline_DSM_cts_ind.dsm-cts-ind-processing_2022-09-06T05_24_26.062835%2B00_00_2.log)

HEAD: a20dde910d092152ca5df4436249fbeb2d91f2e0

Cleared but error persists.

**Comment by nesnoj** [comment]
Uh, this seems to be caused by my changes in #908. Don't we have both scenarios in the test region?

**Comment by nesnoj** [comment]
Handled in #908
