### ISSUE TITLE
Missing dependency `heat_supply` for `HtsEtragoTable`

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#920]
There is a missing dependency of `heat_supply` in  `HtsEtragoTable` .

```(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/storage/eGon-data-sh-je/d_py38_egon-data-cts/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "demand.egon_etrago_timeseries_individual_heating" does not exist
LINE 7:                 demand.egon_etrago_timeseries_individual_hea...
                        ^
```

**Comment by nailend** [comment]
probably solved in #905
