### ISSUE TITLE
Info: there is an internal logging module

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#923]
Just for information @gnn set up an internal logger. As I just found out yesterday I thought it might be interesting for others as well.

Just import the module
`from egon.data import logger`

and write your logs
`logger.info("Info log")`

The message should not contain a "-" as this results into splitting the message and only partially emit it

**Comment by nailend** [comment]
@gnn 
I am receiving the following error. I guess the problem is, having  a '-' in my logging message which you use to split into 2 lines. 
```
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING - --- Logging error in Loguru Handler #1 ---
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING - Record was: {'elapsed': datetime.timedelta(seconds=3, microseconds=461060), 'exception': None, 'extra': {}, 'file': (name='individual_heating.py', path='/storage/egon-data-sh2-je/eGon-data/src/egon/data/datasets/heat_supply/individual_heating.py'), 'function': 'split_mvgds_into_bulks_pypsa_eur_sec', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 1693, 'message': 'Bulk takes care of MVGD: 1337 - 1575', 'module': 'individual_heating', 'name': 'egon.data.datasets.heat_supply.individual_heating', 'process': (id=512025, name='MainProcess'), 'thread': (id=140597893539648, name='MainThread'), 'time': datetime(2022, 10, 15, 12, 0, 21, 77793, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'CEST'))}
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING - Traceback (most recent call last):
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING -   File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING -   File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/loguru/_simple_sinks.py", line 113, in write
    self._function(message)
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING -   File "/storage/egon-data-sh2-je/eGon-data/src/egon/data/__init__.py", line 10, in echo
    prefix, message = message.split(" - ")
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING - ValueError: too many values to unpack (expected 2)
[2022-10-15 12:00:21,078] {logging_mixin.py:120} WARNING - --- End of logging error ---
```

**Comment by nailend** [comment]
> @gnn I am receiving the following error. I guess the problem is, having a '-' in my logging message which you use to split into 2 lines.

Removed the "-" from my logging messages
