### ISSUE TITLE
electrical_neighbours.grid failed in a versioned CI run

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#979]
Latest versioned CI run failed with the following error message: 
`[2022-10-17 16:24:16,059] {taskinstance.py:1150} ERROR - invalid input syntax for type numeric: "inf"
CONTEXT:  COPY egon_etrago_line, line 16, column b: "inf"`

Until now we were not able to identify the reason and want to check whether this bug also appears in a clean run or not.

**Comment by nailend** [comment]
I do also have this problem running SH only. It only appears with a versioned run. Clean run is fine.

```
[2022-10-25 11:23:12,853] {taskinstance.py:1150} ERROR - "None of [Float64Index([nan], dtype='float64', name='bus_id')] are in the [index]"
Traceback (most recent call last):
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/egon-data-sh2-je/eGon-data/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/egon-data-sh2-je/eGon-data/src/egon/data/datasets/electrical_neighbours.py", line 688, in grid
    foreign_dc_lines(scenario, sources, targets, central_buses)
  File "/storage/egon-data-sh2-je/eGon-data/src/egon/data/datasets/electrical_neighbours.py", line 652, in foreign_dc_lines
    foreign_links = etrago.link_geom_from_buses(foreign_links, scenario)
  File "/storage/egon-data-sh2-je/eGon-data/src/egon/data/datasets/etrago_setup.py", line 680, in link_geom_from_buses
    df["geom_1"] = geom_buses.geom[df.bus1.values].values
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/geopandas/geoseries.py", line 608, in __getitem__
    return self._wrapped_pandas_method("__getitem__", key)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/geopandas/geoseries.py", line 601, in _wrapped_pandas_method
    val = getattr(super(), mtd)(*args, **kwargs)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/series.py", line 966, in __getitem__
    return self._get_with(key)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/series.py", line 1006, in _get_with
    return self.loc[key]
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/storage/egon-data-sh2-je/d_py38_egon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Float64Index([nan], dtype='float64', name='bus_id')] are in the [index]"
```

**Comment by ClaraBuettner** [comment]
This issue is a duplicate to #906
